### ISSUE TITLE
implied columns do not show up in the sample annotation sheet

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#10]
in the project sample I made here, the implied columns are available for derived columns, but do not actually appear in the annotation sheet.

https://github.com/pepkit/pephub

**Comment by stolarczyk** [comment]
Did you try to use the code from the `dev` branch? The implied attributes appear in the `samples()` output in this vignette: https://github.com/pepkit/pepr/blob/dev/vignettes/derivedImpliedAttributes.Rmd.

I've also tried the old naming scheme (`*_columns`) and it also works.

**Comment by nsheff** [comment]
yes, it does work on dev. Thanks!

in the future dev should have a different version than master if it differs.
