### ISSUE TITLE
expandPath problem

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/pepr#14]
The `expandPath` function deletes the double slashes that are needed in the URLs  when used in the derived attributes in the config.

Like [here](https://github.com/pepkit/example_peps/blob/master/example_BiocProject/project_config.yaml)

**Comment by nsheff** [comment]
Related to earlier fix of #7 I guess.

**Comment by nsheff** [comment]
expandPath does not appear to be working on `dev`. When I try to run the code in the getting started vignette, I see this:

```
> projectConfig = system.file("extdata",
+ "example_peps-master",
+ "example_basic",
+ "project_config.yaml",
+ package = "pepr")
> p = Project(file = projectConfig)
Loaded config file:  
/sfs/qumulo/qhome/ns5bc/R/x86_64-pc-linux-gnu-library/3.4/pepr/extdata/example_peps-master/example_basic/project_config.yaml
Warning message:
In makeMetadataSectionAbsolute(cfg, parent = dirname(filename)) :
  Value for 'output_dir' doesn't exist: '/sfs/qumulo/qhome/ns5bc/R/x86_64-pc-linux-gnu-library/3.4/pepr/extdata/example_peps-master/example_basic/$HOME/hello_looper_results'
```

See how `$HOME` has not been expanded?

**Comment by stolarczyk** [comment]
The function is looking for `${ENV_VAR_NAME}` as in this [project config example](https://github.com/pepkit/example_peps/blob/master/example_BiocProject/project_config.yaml). I'll try to fix it

**Comment by nsheff** [comment]
I see. We can't assume those variables will be bracketed. I think the old function correctly handled these.
