### ISSUE TITLE
broken vignette links

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#17]
all advanced vignettes include text like this:

> For a broader theoretical description of sample subannotation click here.

Can we change int the following ways: 
1. Those links are broken in many cases (for `implied_attributes` instead of `implied_columns`)
2. Never use 'here' as link anchor text.

**Comment by nsheff** [comment]
I also think this is not necessary on every page : "For introductory information about the package visit the documentation page. "

**Comment by stolarczyk** [comment]
> 1. Those links are broken in many cases (for `implied_attributes` instead of `implied_columns`)

Should we change the name of the sub pages that these links point to (`*_columns` -> `*_attributes` )? Then everything would follow the new naming scheme.

**Comment by nsheff** [comment]
Sure, let's do it that way.

**Comment by nsheff** [comment]
just have to make sure to change any links  on other pages -- or make the old links forward to the new ones. those have been that way for awhile.

**Comment by stolarczyk** [comment]
> just have to make sure to change any links on other pages -- or make the old links forward to the new ones. those have been that way for awhile.

Fixed in: https://github.com/pepkit/pepkit.github.io/commit/5ed0de118afff740d0df18f321a01c22c583d70f
