### ISSUE TITLE
 Warning: Value for 'output_dir' doesn't exist:

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#18]
In many of our examples, we see text like this:
```
 Warning: Value for 'output_dir' doesn't exist: '/Users/mstolarczyk/hello_looper_results'
```

I'm wondering if we should just disable that warning... thoughts?

**Comment by nsheff** [comment]
here's an example of what I mean;

http://code.databio.org/pepr/reference/config-Project-method.html

this is jarring in help documentation.

**Comment by stolarczyk** [comment]
The `output_dir` is not used in any of the minimal examples. Maybe we can just delete these lines from the config files? 

The warning is useful for the real projects, I think.

**Comment by nsheff** [comment]
I think I would just take out the warning. I don't see it being useful even for real projects. it depends too much on what the project is.
