### ISSUE TITLE
listSubprojects() should accept project

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#20]
I think `listSubprojects` should use a project object as an argument, not a `Config`.

Is there a reason to do it that way?

**Comment by stolarczyk** [comment]
This function is used in the `loadConfig` function. There's no `Project` object created at that point.

**Comment by nsheff** [comment]
oh ok. I was thinking it would be useful to have a function that lists the subprojects of the Project, for the user to use. I guess that would be a different function -- or `listSubprojects` could accept either. 
does that seem useful?

**Comment by nsheff** [comment]
maybe put another way: if `listSubprojects` is exported, I feel it should take a `Project`.  that is most intuitive for the user, and that's what exported functions are for.

then we could have an internal one that is not exported that uses a config.

**Comment by stolarczyk** [comment]
Now the function takes the `Project` object by default, but if the `Config` object is provided (just like in our internal use) it still does the job.
