### ISSUE TITLE
pepr not installable in later versions of R

### ISSUE THREAD

**Issue by KasperThystrup** [pepkit/pepr#47]
If possible, please reupload your pacakge to CRAN for the latest version of R.

```
install.packages("pepr")
...
package ‘pepr’ is not available for this version of R
```

Info on my setup:
```
devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Denmark.utf8
 ctype    English_Denmark.utf8
 tz       Europe/Copenhagen
 date     2023-10-24
 rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
 pandoc   NA
```

**Comment by KasperThystrup** [comment]
Bonus info - following the source page on [CRAN](https://cran.r-project.org/web/packages/pepr/index.html).
`Archived on 2023-08-19 as email to the maintainer is undeliverable. `

**Comment by nsheff** [comment]
Thanks for the note, I'm trying to fix it now. Until I get this fixed, you can always install from github if that's helpful:

```
devtools::install_github("pepkit/pepr")
```

**Comment by nsheff** [comment]
pepr 0.5.0 has been released on CRAN: https://cran.r-project.org/web/packages/pepr/index.html
