### ISSUE TITLE
Path expand malfunction?

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/pepr#5]
The `expandPath` function returns invaild path string, e.g.

`> pepr::expandPath("~/UVA")` yields `"//home/mjs5kd/UVA"`

Moreover, it doubles the r base package functionality in `path.expand`, which returns a proper path

**Comment by nsheff** [comment]
What do you mean that's an invalid string? Because it has a double slash?

The base one doesn't expand environment variables...

**Comment by stolarczyk** [comment]
Yes, you're right. That's why I closed the issue. Sorry
