### ISSUE TITLE
Need to add subprojects support

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/pepr#8]
Add subprojects, see `peppy`: https://peppy.readthedocs.io/en/latest/define-your-project.html?highlight=subproject

**Comment by nsheff** [comment]
if I remember right, at one point there was subprojects support in there. do they not work anymore?

**Comment by stolarczyk** [comment]
Yes, there is subproject support, I just need to make some changes for it to work with the functionalities that I've added recently + corresponding vignettes and examples
