### ISSUE TITLE
Eliminate direct slot accessors from documentation

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepr#9]
in all documentation, let's  change slot accessor code (`p@config`) to use the accessor functions (`config(p)`) because that is the preferred way for R objects (it doesn't expose the underlying object slot architecture.).

we need to change this in all vignettes and also the readme: https://github.com/pepkit/pepr

**Comment by nsheff** [comment]
say something like this: 

access samples this way:

```
samples(p)
config(p)
```

it's also possible to access the slots direclty, but his is not preferred because it is not guarnteed and may change:
```
p@config
p@samples
```

**Comment by nsheff** [comment]
@michalstolarczyk  can you also keep an eye on this page? 

https://pepkit.github.io/docs/pepr/

the @s are still there

**Comment by stolarczyk** [comment]
done
